# Generated by Django 2.2.1 on 2019-09-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_userstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstock',
            name='id',
        ),
        migrations.AlterField(
            model_name='userstock',
            name='username',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
