# Generated by Django 2.2.1 on 2019-09-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190929_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='ticker',
            field=models.TextField(),
        ),
    ]
