# Generated by Django 2.2.1 on 2019-08-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190822_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='titles',
        ),
    ]
