# Generated by Django 2.2.1 on 2019-08-23 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190823_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='titles',
            new_name='title',
        ),
    ]
